name    : HoangD
author  : HoangD
description: GithubHackathon
inputs  : 
    inputs:
  numOctocats:
    description: 'Number of Octocats'
    required: false
    default: '1'
  octocatEyeColor:
    description: 'Eye color of the Octocats'
    required: true
